[build]
publish = "public/"
functions = "functions/"

[dev]
framework = "#static"

[[redirects]]
from = "/"
to = "https://github.com/ArkaneMoose/gatech-academic-calendar-regenerator"

[[redirects]]
from = "/calendar.ics"
to = "/.netlify/functions/calendar"
status = 200
